### PR TITLE
fix(datastore) Make PendingMutationConverter work for SerializedModel

### LINKED ISSUE #1199: DataStore synch problem during offline item saving
Hi, this issue is related to #823 which has been closed, but actually is still a problem and is easy to recreate by using [the main Android tutorial](https://docs.amplify.aws/start/getting-started/setup/q/integration/android).

The problem occurs while saving an item during an offline condition, stop the program for any reason and start the program again: this way the local and remote items have a mismatch.

I'm using the latest version of Amplify Framework (1.16.13).

My environment:
 - Android Studio 4.1.2
 - Target API 30, minSdkVersion 26

The scenario related to #823 is neither A nor B: if you apply scenario B everything works, BUT, if you stop the program after each save, the issue is there (local data and cloud data mismatch).

So the steps to recreate the issue are:
 1.  Set the device in online mode (wifi or mobile data active), run the program (same one of the tutorial) from Android Studio, save an item (Item 1) inside `onCreate()` method.
 2.  Query the saved item inside the program (`Amplify.DataStore.query()`): check the local Item 1 is there.
 3.  Query the saved item inside DynamoDB or by using AppSync Console command:
       ```graphql
     query GetTodos { listTodos { items { id name priority description } } }
     ```
     Check the remote Item 1 is there also.
      The Item 1 is correctly stored both locally and remotely.
 4.  **Important**: stop the program (Red stop button in Android Studio).
 5. Set the device in offline mode (disable wifi and mobile data), run again the program from Android Studio, save a second item (Item 2) inside OnCreate() method: this item will be saved locally, not in the cloud.
 6. Query the saved item inside the program (Amplify.DataStore.query()): check the local Item 2 is there.
 7.  **Important**: stop the program again (Red stop button in Android Studio).
 8. Set the device in online mode again (wifi or mobile data active), run again the program from Android Studio, save a third item (Item 3) inside OnCreate() method.

Right now we expect that during step 8, the framework will save remotely both Item 2 (which was not saved in step 5 due to the lack of mobile connection) and Item 3, but only Item 3 is saved. If you query locally you'll get all three items. If you query remotely (DynamoDB and AppSync console) you get only Item 1 and 3, Item 2 is lost forever, no matter how many connections or DataStore API calls you make. If you do an `Amplify.DataStore.clear()` after that, Item 2 is gone forever.

This is definitely something the Framework should handle.

Let me know if you need more info to recreate the issue.

### PR DESCRIPTION
**Pull request by richardmcclellan**
There were two bugs introduced by https://github.com/aws-amplify/amplify-android/pull/1110, which changed the update mutation behavior to only send fields that had _changed_.  To do that, we convert the Java models to `SerializedModel` objects, because it allows us to represent the absence of a field, since the field is stored as a `Map`:

1. Items saved while offline (and thus persisted into the `PendingRecord` SQLite table) were not persisted correctly, and the mutations ended up getting sent to AppSync with all of the fields set to null, except for "id". (https://github.com/aws-amplify/amplify-android/issues/1199).  I've fixed this by updating the `PendingMutationConverter` to actually work for `SerializedModel` objects.

2. Mutations for models with children weren't created properly.    `ModelConverter.toMap` (added in the previously mentioned PR) just used Gson to convert a Java model to a Map.  This is not sufficient for serializing models with children, because the association fields just the child's ID needs to be serialized, not the whole child object.  

Fixes #1199

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

File: aws-api-appsync/src/main/java/com/amplifyframework/datastore/appsync/ModelConverter.java [hunk 1]
```diff
@@ -34,33 +34,64 @@ private ModelConverter() {}
...
-            return ((SerializedModel) model).getSerializedData();
+        return result;
+    }
+
+    private static Object extractAssociateId(ModelField modelField, Model instance)
+            throws NoSuchFieldException, IllegalAccessException {
+        final Object fieldValue = extractFieldValue(modelField, instance);
+        if (modelField.isModel() && fieldValue instanceof Model) {
+            return ((Model) fieldValue).getId();
+        } else if (modelField.isModel() && fieldValue instanceof Map) {
```
Comment (jamesonwilliams) [inline aws-api-appsync/src/main/java/com/amplifyframework/datastore/appsync/ModelConverter.java:77]: Is this a valid case to consider?

```java
} else if (modelField.isModel() && fieldValue instanceof SerializedModel) {
...
}
```

File: aws-datastore/src/test/java/com/amplifyframework/datastore/storage/sqlite/SQLCommandProcessorTest.java [hunk 2]
```diff
@@ -122,7 +124,8 @@ public void rawQueryReturnsResults() throws AmplifyException {
         if (cursor.moveToFirst()) {
             do {
                 Map<String, Object> map = converter.buildMapForModel(cursor);
-                results.add(ModelConverter.fromMap(map, BlogOwner.class));
+                String jsonString = gson.toJson(map);
+                results.add(gson.fromJson(jsonString, BlogOwner.class));
```
Comment (jamesonwilliams) [inline aws-datastore/src/test/java/com/amplifyframework/datastore/storage/sqlite/SQLCommandProcessorTest.java:128]: Don't we have a higher-level utility somewhere that does the object->json->model double conversion, without calling `Gson` directly?

**Review by jamesonwilliams — APPROVED** [review]

File: aws-api-appsync/src/main/java/com/amplifyframework/datastore/appsync/ModelConverter.java (hunk 1 above)
Comment (richardmcclellan) [reply aws-api-appsync/src/main/java/com/amplifyframework/datastore/appsync/ModelConverter.java:77]: No, at least not right now.  Right now, we don't ever construct trees with `SerializedModel`s.   A `SerializedModel` only stores the `id` of its children, not any of the child data.   I think we will need to do that in the future, to fully move from Java models to SerializedModel's, internally, but that's a bigger change.

File: aws-datastore/src/test/java/com/amplifyframework/datastore/storage/sqlite/SQLCommandProcessorTest.java (hunk 2 above)
Comment (richardmcclellan) [reply aws-datastore/src/test/java/com/amplifyframework/datastore/storage/sqlite/SQLCommandProcessorTest.java:128]: Previously, I had added a `ModelConverter::fromMap` method, that did just that.   It was used here, and in the SQLiteStorageAdapter.   I actually removed it in this PR because `fromMap`, which uses Gson, isn't congruent with `toMap`, which uses the `ModelSchema`.    Using Gson does work for this particular use case, but I'm not sure it works for all use cases.

**Review by rjuliano — APPROVED** [review]
LGTM 🚢

**Comment by richardmcclellan** [comment]
I did some more testing with this PR, and mutations with children are failing, so I'm working on a fix now.

**Review by jamesonwilliams — APPROVED** [review]

**Review by rjuliano — APPROVED** [review]
Ship it 🚢
