### PR TITLE
fix(auth): fetch device metadata from credential store for `remember` and `forgetDevice`

### LINKED ISSUE #2585: Auth rememberDevice — InvalidParameterException, value null at 'deviceKey'
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-android/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-android/discussions).

### Language and Async Model

Kotlin - Coroutines

### Amplify Categories

Authentication

### Gradle script dependencies

<details>

```groovy
    def amplifyVersion = '2.11.2'
    implementation "com.amplifyframework:core:$amplifyVersion"
    implementation "com.amplifyframework:aws-auth-cognito:$amplifyVersion"
    implementation "com.amplifyframework:aws-api:$amplifyVersion"
    implementation "com.amplifyframework:aws-storage-s3:$amplifyVersion"
```

</details>

### Environment information

<details>

```
------------------------------------------------------------
Gradle 8.0
------------------------------------------------------------

Build time:   2023-02-13 13:15:21 UTC
Revision:     62ab9b7c7f884426cf79fbedcf07658b2dbe9e97

Kotlin:       1.8.10
Groovy:       3.0.13
Ant:          Apache Ant(TM) version 1.10.11 compiled on July 10 2021
JVM:          17.0.7 (Eclipse Adoptium 17.0.7+7)
OS:           Mac OS X 13.4 x86_64
```

</details>

### Please include any relevant guides or documentation you're referencing

https://docs.amplify.aws/lib/auth/device_features/q/platform/android/#configure-auth-category

### Describe the bug

I'm trying to block users from signing-in on multiple devices concurrently. My attempted solution is to block the user's progress if Auth.fetchDevices() returns multiple devices, or call Auth.rememberDevice() if there are no tracked devices. This works on a fresh install, first pass. Then when the user signs-out, I call Auth.forgetDevice(). After which, calling Auth.rememberDevice() when signing-in again returns the InvalidParameterException. 

I've seen a [similar thread for Amplify JS](https://github.com/aws-amplify/amplify-js/issues/3040). The proposed solution there is to call a `cognitoUser.getCachedDeviceKeyAndPassword()` method, which I can't find for Android.

### Reproduction steps (if applicable)

1. Auth.signIn() -> Auth.rememberDevice()
2. Auth.forgetDevice() -> Auth.signOut()
3. Auth.signIn() -> Auth.rememberDevice()
4. Exception thrown by rememberDevice()

### Code Snippet

```kotlin
override suspend fun rememberDevice(): Result<Unit> = suspendCoroutine { continuation ->
    auth.rememberDevice(
        /* onSuccess = */ {
            continuation.resume(Result.success(Unit))
        },
        /* onError = */ { error ->
            logger.logError(error)
            continuation.resume(Result.failure(error))
        }
    )
}

```

### Log output

<details>

```
InvalidParameterException{message=One or more parameters are incorrect., cause=InvalidParameterException(message=1 validation error detected: Value null at 'deviceKey' failed to satisfy constraint: Member must not be null), recoverySuggestion=Enter correct parameters.}
	at com.amplifyframework.auth.cognito.CognitoAuthExceptionConverter$Companion.lookup(CognitoAuthExceptionConverter.kt:70)
	at com.amplifyframework.auth.cognito.RealAWSCognitoAuthPlugin$updateDevice$1.invokeSuspend(RealAWSCognitoAuthPlugin.kt:1132)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.UndispatchedCoroutine.afterResume(CoroutineContext.kt:270)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.UndispatchedCoroutine.afterResume(CoroutineContext.kt:270)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)


```

</details>

### amplifyconfiguration.json

_No response_

### GraphQL Schema

<details>

```graphql
// Put your schema below this line


```

</details>

### Additional information and screenshots

_No response_

### PR DESCRIPTION
**Pull request by tjleing**
fixes #2585.

- [ ] PR title and description conform to [Pull Request](https://github.com/aws-amplify/amplify-android/blob/main/CONTRIBUTING.md#pull-request-guidelines) guidelines.

*Issue #, if available:*

*Description of changes:*
If Cognito returns `null` `newDeviceMetadata` uses our previously-existing metadata if we have it.  That goes directly into the AuthN state, so reading it immediately after a `signIn` will return null.

After digging into it for a while, I discovered that Swift does things differently than we currently do -- [Swift line](https://github.com/aws-amplify/amplify-swift/blob/49a248b99fc0764573e82c44d35f7e6bb4cc8b63/AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Task/DeviceTasks/AWSAuthRememberDeviceTask.swift#L60) vs [Android line](https://github.com/aws-amplify/amplify-android/blob/3e5e8695ffaaaba280fbffa19587b593442d97d7/aws-auth-cognito/src/main/java/com/amplifyframework/auth/cognito/RealAWSCognitoAuthPlugin.kt#L1227).  This essentially copies Swift's method of doing things.  Note that this might mean we could be able to remove `deviceMetadata` from `AuthenticationState.SignedIn` since I believe we don't actually use it anymore.

For review: do we prefer `runBlocking` or `GlobalScope.launch` (or `GlobalScope.async`)?  I'm seeing more `GlobalScope.launch` in the code that's already here so I went with that.

*How did you test these changes?*
(Please add a line here how the changes were tested)
Sample app

*Documentation update required?*
- [x] No
- [ ] Yes (Please include a PR link for the documentation update)

*General Checklist*
- [ ] Added Unit Tests
- [ ] Added Integration Tests
- [ ] Security oriented best practices and standards are followed (e.g. using input sanitization, principle of least privilege, etc)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

File: aws-auth-cognito/src/main/java/com/amplifyframework/auth/cognito/RealAWSCognitoAuthPlugin.kt [hunk 1]
```diff
@@ -1223,12 +1222,14 @@ internal class RealAWSCognitoAuthPlugin(
         authStateMachine.getCurrentState { authState ->
             when (val state = authState.authNState) {
                 is AuthenticationState.SignedIn -> {
-                    updateDevice(
-                        (state.deviceMetadata as? DeviceMetadata.Metadata)?.deviceKey,
-                        DeviceRememberedStatusType.Remembered,
-                        onSuccess,
-                        onError
-                    )
+                    GlobalScope.launch {
```
Comment (gpanshu) [inline aws-auth-cognito/src/main/java/com/amplifyframework/auth/cognito/RealAWSCognitoAuthPlugin.kt:1225]: runBlocking and GlobalScope both will have the same outcome here since there is nothing to execute after globalScope it will just finish when it finishes while starting a coroutine vs a runblocking will block the thread.

File: aws-auth-cognito/src/main/java/com/amplifyframework/auth/cognito/RealAWSCognitoAuthPlugin.kt [hunk 2]
```diff
@@ -1223,12 +1222,14 @@ internal class RealAWSCognitoAuthPlugin(
...
+                        updateDevice(
+                            authEnvironment.getDeviceMetadata(state.signedInData.username)?.deviceKey,
+                            DeviceRememberedStatusType.Remembered,
```
Comment (gpanshu) [inline aws-auth-cognito/src/main/java/com/amplifyframework/auth/cognito/RealAWSCognitoAuthPlugin.kt:1228]: Can you add tests to check this as well ?

File: aws-auth-cognito/src/main/java/com/amplifyframework/auth/cognito/RealAWSCognitoAuthPlugin.kt [hunk 3]
```diff
@@ -1276,8 +1277,11 @@ internal class RealAWSCognitoAuthPlugin(
             when (val authState = authState.authNState) {
                 is AuthenticationState.SignedIn -> {
                     if (device.id.isEmpty()) {
-                        val deviceKey = (authState.deviceMetadata as? DeviceMetadata.Metadata)?.deviceKey
-                        updateDevice(deviceKey, DeviceRememberedStatusType.NotRemembered, onSuccess, onError)
+                        GlobalScope.launch {
+                            val deviceKey = authEnvironment.getDeviceMetadata(authState.signedInData.username)
```
Comment (gpanshu) [inline aws-auth-cognito/src/main/java/com/amplifyframework/auth/cognito/RealAWSCognitoAuthPlugin.kt:1281]: Can you add tests to check this as well ?

**Review by tylerjroach — APPROVED** [review]

**Review by gpanshu — APPROVED** [review]
